name: new_proj_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.4
  googleapis: ^10.0.0
  googleapis_auth: ^1.4.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.13
  intl: ^0.19.0
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.web"
